export {
  listJobs,
  getJobById,
  listApplications,
  getApplicationById,
  listCompanies,
  getCompanyById,
  getJobsByCompanyName,
  listActivities,
  getDashboardStats,
  getJobsBySourceChart,
  getApplicationsByStatusChart,
} from './mock/ui-adapters';

export type {
  Profile,
  ProfileInsert,
  ProfileUpdate,
  CompanyRecord,
  CompanyInsert,
  CompanyUpdate,
  Contact,
  ContactInsert,
  ContactUpdate,
  JobRecord,
  JobInsert,
  JobUpdate,
  JobAnalysis,
  JobAnalysisInsert,
  ApplicationRecord,
  ApplicationInsert,
  ApplicationUpdate,
  ApplicationArtifact,
  ActivityRecord,
  ProfilesRepository,
  CompaniesRepository,
  ContactsRepository,
  JobsRepository,
  JobAnalysisRepository,
  ApplicationsRepository,
  ApplicationArtifactsRepository,
  ActivitiesRepository,
} from './contracts';
